---
- hosts: localhost
  connection: local
  gather_facts: no

# Setting vars for this App 

  vars:
      destination_host: localhost
      destination_port: 32768
      netbox_token: 0123456789abcdef0123456789abcdef01234567
  
# Running tasks

  tasks:
      - name: REST API CALL / GET
        uri:
            url: http://{{ destination_host }}:{{ destination_port }}/{{ resource_path }}
            method: GET
            headers:
                Authorization: "Token {{ netbox_token }}"
        register: rest_get
        vars:
            resource_path: api/dcim/devices/

      - name: DEBUG / GOT INFO
        debug:
            msg: "{{ rest_get.json }}"
...
