---
- hosts: localhost
  connection: local
  gather_facts: no

# Setting vars for this App 

  vars:
      destination_host: localhost
      destination_port: 32768
      netbox_token: 0123456789abcdef0123456789abcdef01234567
  
# Running tasks

  tasks:
      - name: REST API CALL / PUT
        uri:
            url: http://{{ destination_host }}:{{ destination_port }}/{{ resource_path }}/{{ id }}/
            method: PUT
            headers:
                Authorization: "Token {{ netbox_token }}"
            body_format: json
            body:
                device_type: 3
                device_role: 3
                site: 1
                status: 3
        ignore_errors: yes
        register: rest_post
        vars:
            resource_path: api/dcim/devices
            id: 32
...
